version: 2
updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
      day: saturday
      time: "00:00"
      timezone: Asia/Tokyo
  - directory: /
    package-ecosystem: cargo
    schedule:
      interval: weekly
      day: saturday
      time: "00:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 50
