name: CI

permissions:
  checks: write
  contents: read

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up rust-toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Test
        run: |
          cargo test
      - name: Run clippy
        uses: sksat/action-clippy@v1.1.1
        with:
          reporter: github-check
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up rust-toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Build
        run: |
          cargo build --release
